{application,server,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{server_app,[]}},
              {env,[]},
              {modules,[parser,room,server,server_app,server_sup,
                        tcp_handler]}]}.
